name: Build

on: 
  repository_dispatch:
  workflow_dispatch:
  #schedule:
    #- cron: 0 23 * * 5

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    #if: github.repository_owner=='a0575'
    env:
      build_variant: ${{ matrix.build_variant }}
      targets: ${{ matrix.targets }}
      images_dir: /opt/images
    strategy:
      matrix:
        include:
          - build_variant: "A1"
            targets: "MI-3A"
          - build_variant: "A2"
            targets: "MI-3C"
          - build_variant: "A3"
            targets: "PSG1218"
          - build_variant: "A4"
            targets: "JCG-Q10-Pro"
            
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Clone source code
        run: |
          git clone --depth=1 https://github.com/hanwckf/rt-n56u.git /opt/rt-n56u
          #git clone --depth=1 https://github.com/hiboyhiboy/rt-n56u.git /opt/rt-n56u
          #git clone --depth=1 https://github.com/a0575/padavan.git /opt/rt-n56u
          cp -rf . /opt/rt-n56u
          cd /opt/rt-n56u

      - name: Prepare environment
        run: |
          sudo apt-get update
          sudo apt-get install libtool-bin gperf python3-docutils autopoint gettext
        
      - name: Run shellcheck
        run: |
          cd /opt/rt-n56u
          if [ -e scripts/ ]; then
            cp -r scripts/. trunk/
          fi
          sh ./trunk/tools/shellcheck.sh
        
      - name: Prepare toolchain
        run: |
          cd /opt/rt-n56u
          cd toolchain-mipsel
          sh dl_toolchain.sh
        
      - name: Start build
        run: |
          cd /opt/rt-n56u
          cd trunk
          mkdir -p ${images_dir}
          for m in $targets; do fakeroot ./build_firmware_ci $m; \
          if [ $? = 0 ]; then cp -f images/*.trx ${images_dir}/$m.trx; else exit 1; fi; \
            ./clear_tree_simple >/dev/null 2>&1; done

      - name : Upload packages
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: Padavan-packages
          path: /opt/images
